# List the data sources used to create urls.
urlFile: 'urls.txt'
sources:
  urls: 'data/urls.csv'

hosts:
  local: 'http://localhost'

profiles:
  test:
    basePath: '/'
    host: local
    sourcePct:
      sps: .5
    settings:
      useRootUrls: true

# Default arg values.
defaults:
  profile: test
  count: 10
